version: '3.8'

services:
  omie_app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        HOST: 5050
        PORT: 0.0.0.0
    ports:
      - "5050:5050"
    environment:
      - PYTHONUNBUFFERED=1